# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  registry = {
    pname = "registry";
    version = "98f4a21a86069a26da28dd991e035ea9e972af18";
    src = fetchFromGitHub {
      owner = "codedownio";
      repo = "General";
      rev = "98f4a21a86069a26da28dd991e035ea9e972af18";
      fetchSubmodules = false;
      sha256 = "sha256-Nz363UFfFUTmCoTOBK0jYuSfCDkK7emhJ2MnDkEoIGo=";
    };
    date = "2025-12-12";
  };
}
